services:
  tansucloud.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    container_name: gateway
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  tansucloud.identity:
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - NPGSQL__HOST=db
      - NPGSQL__PORT=5432
    ports:
      - "8081:8080"
    container_name: identity

  db:
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"