services:
  # Development-only host port bindings. Do not use in production.
  tansucloud.gateway:
    ports:
      - "8080:8080"

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"
