global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:8080','tansucloud.gateway:8080']
  - job_name: 'identity'
    metrics_path: /metrics
    static_configs:
      - targets: ['identity:8080','tansucloud.identity:8080']
